name: Manual Docker Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (e.g., v1.6.0)'
        required: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: danielng123/nr-mcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version number
        id: version
        run: echo "VERSION=$(echo ${{ github.event.inputs.tag }} | sed 's/^v//')" >> $GITHUB_OUTPUT
      
      - name: Fetch all tags to determine latest
        run: git fetch --tags
        
      - name: Check if tag is latest
        id: check_latest
        run: |
          # Get the latest tag by version sorting
          LATEST_TAG=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag is: $LATEST_TAG"
          
          # Check if current tag is the latest
          if [ "${{ github.event.inputs.tag }}" = "$LATEST_TAG" ]; then
            echo "IS_LATEST=true" >> $GITHUB_OUTPUT
            echo "This is the latest tag"
          else
            echo "IS_LATEST=false" >> $GITHUB_OUTPUT
            echo "This is not the latest tag"
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.VERSION }}
            ${{ steps.check_latest.outputs.IS_LATEST == 'true' && 'type=raw,value=latest' || '' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
